### ISSUE TITLE
请求：添加命令行参数，指定服务端口

### ISSUE THREAD

**Issue by Hanekihyouka** [longtimenotalk2/OJBattle#2]
希望运行这个 cli 程序的时候，可以像这样 `./OJBattle -p port` 指定端口。不指定的时候再默认用 8080。
8080 太常用了，会有很多服务占。

我不会 rust。

**Comment by Hanekihyouka** [comment]
另外请求将服务的默认地址设置为 0.0.0.0 而非 127.0.0.1 。

**Comment by longtimenotalk2** [comment]
> 希望运行这个 cli 程序的时候，可以像这样 `./OJBattle -p port` 指定端口。不指定的时候再默认用 8080。 8080 太常用了，会有很多服务占。
> 
> 我不会 rust。

已解决
